# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Tag CRUD on Postgres.

Concentrated on the name rule, which is the only part of a tag that is not a
plain row: unique case-insensitively on the *trimmed* name. It is enforced
twice — by a check in ``create_tag`` and by ``uq_tag_name_lower`` underneath it
— so the tests cover both halves. The index is the one that matters, because it
is what holds when the check loses a race, and an index is exactly the sort of
thing an autogenerated migration silently drops.

Needs a migrated database and skips without one.
"""

from __future__ import annotations

import os
import uuid

import pytest

pytest.importorskip("sqlalchemy")

from sqlalchemy.exc import IntegrityError  # noqa: E402

from gsf.dal import schema as s  # noqa: E402
from gsf.dal.session import store  # noqa: E402
from gsf.dal.tags import create_tag, delete_tag, list_tags  # noqa: E402


@pytest.fixture(scope="module", autouse=True)
def require_schema():
    if not os.environ.get("POSTGRES_USER"):
        pytest.skip("POSTGRES_* not set")
    try:
        store().query_read("SELECT 1 FROM tag LIMIT 1")
    except Exception as exc:  # noqa: BLE001
        pytest.skip(f"gsf schema unavailable (alembic upgrade head): {exc}")


@pytest.fixture
def prefix():
    """A name prefix unique to this test, and its cleanup."""
    value = f"t-{uuid.uuid4().hex[:8]}"
    yield value
    store().query_write(s.tag.delete().where(s.tag.c.name.like(f"%{value}%")))


def test_create_returns_the_stored_tag(prefix) -> None:
    tag = create_tag(name=f"{prefix}-pii")

    assert tag["name"] == f"{prefix}-pii"
    assert tag["id"]


def test_the_same_name_twice_is_rejected(prefix) -> None:
    create_tag(name=f"{prefix}-pii")

    with pytest.raises(ValueError, match="already exists"):
        create_tag(name=f"{prefix}-pii")


def test_the_name_rule_ignores_case(prefix) -> None:
    """A plain UNIQUE column would admit these two side by side."""
    create_tag(name=f"{prefix}-PII")

    with pytest.raises(ValueError, match="already exists"):
        create_tag(name=f"{prefix}-pii")


def test_the_name_rule_ignores_surrounding_whitespace(prefix) -> None:
    create_tag(name=f"{prefix}-pii")

    with pytest.raises(ValueError, match="already exists"):
        create_tag(name=f"  {prefix}-pii  ")


def test_the_index_rejects_a_duplicate_the_check_never_saw(prefix) -> None:
    """The half that holds under a race: insert straight past ``create_tag``.

    Two concurrent creates can both pass the duplicate check before either
    inserts. This is that window, forced — and what makes it safe is the index,
    not the check.
    """
    create_tag(name=f"{prefix}-pii")

    with pytest.raises(IntegrityError):
        store().query_write(s.tag.insert().values(name=f"{prefix}-PII  "))


def test_different_names_coexist(prefix) -> None:
    create_tag(name=f"{prefix}-pii")
    create_tag(name=f"{prefix}-gdpr")

    names = [row["name"] for row in list_tags() if prefix in row["name"]]
    assert names == [f"{prefix}-gdpr", f"{prefix}-pii"]


def test_the_listing_is_ordered_case_insensitively(prefix) -> None:
    """``ORDER BY name`` would put every capital ahead of every lowercase."""
    for name in (f"{prefix}-beta", f"{prefix}-Alpha", f"{prefix}-gamma"):
        create_tag(name=name)

    names = [row["name"] for row in list_tags() if prefix in row["name"]]
    assert names == [f"{prefix}-Alpha", f"{prefix}-beta", f"{prefix}-gamma"]


def test_create_stamps_both_timestamps(prefix) -> None:
    """Both come from the database, and a fresh tag has not been modified."""
    tag = create_tag(name=f"{prefix}-pii")

    assert tag["created"].tzinfo is not None
    assert tag["modified"] == tag["created"]


def test_the_timestamps_survive_the_listing(prefix) -> None:
    """The list and create paths return the same shape -- ``_COLUMNS``."""
    created = create_tag(name=f"{prefix}-pii")

    listed = next(row for row in list_tags() if row["id"] == created["id"])
    assert listed == created


def test_an_update_advances_modified_and_leaves_created(prefix) -> None:
    """``onupdate`` is SQLAlchemy-side, so it only fires for DAL-issued writes.

    There is no rename endpoint yet, which is exactly why this is worth
    pinning: the column's whole contract is that whoever adds one gets the
    timestamp for free rather than having to remember it.
    """
    tag = create_tag(name=f"{prefix}-pii")

    store().query_write(
        s.tag.update().where(s.tag.c.id == tag["id"]).values(name=f"{prefix}-gdpr")
    )

    updated = next(row for row in list_tags() if row["id"] == tag["id"])
    assert updated["created"] == tag["created"]
    assert updated["modified"] > tag["modified"]


def test_delete_removes_the_tag(prefix) -> None:
    tag = create_tag(name=f"{prefix}-pii")

    assert delete_tag(tag["id"]) is True
    assert [row for row in list_tags() if row["id"] == tag["id"]] == []


def test_deleting_a_tag_that_is_not_there_reports_it(prefix) -> None:
    """What the router turns into a 404 instead of a silent success."""
    assert delete_tag(f"{prefix}-no-such-id") is False


def test_deleting_a_tag_frees_its_name(prefix) -> None:
    """The unique index covers live rows only, so the name comes back."""
    tag = create_tag(name=f"{prefix}-pii")
    delete_tag(tag["id"])

    assert create_tag(name=f"{prefix}-pii")["id"] != tag["id"]
