"""add tag_target table

Revision ID: 00e5822e88be
Revises: 9e95a9a81a47
Create Date: 2026-09-03 12:23:24.769634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00e5822e88be"
down_revision: Union[str, Sequence[str], None] = "9e95a9a81a47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag_target",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("(gen_random_uuid())::text"),
            nullable=False,
        ),
        sa.Column("tag_id", sa.Text(), nullable=False),
        sa.Column("term_id", sa.Text(), nullable=True),
        sa.Column("table_id", sa.Text(), nullable=True),
        sa.Column("column_id", sa.Text(), nullable=True),
        sa.Column("column_attribute_id", sa.Text(), nullable=True),
        sa.Column("sql_attribute_id", sa.Text(), nullable=True),
        sa.Column(
            "tagged",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nonnulls(term_id, table_id, column_id, column_attribute_id, sql_attribute_id) = 1",
            name=op.f("ck_tag_target_exactly_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["column_attribute_id"],
            ["column_attribute.id"],
            name=op.f("fk_tag_target_column_attribute_id_column_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["catalog_column.id"],
            name=op.f("fk_tag_target_column_id_catalog_column"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sql_attribute_id"],
            ["sql_attribute.id"],
            name=op.f("fk_tag_target_sql_attribute_id_sql_attribute"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["catalog_table.id"],
            name=op.f("fk_tag_target_table_id_catalog_table"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
            name=op.f("fk_tag_target_tag_id_tag"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["term.id"],
            name=op.f("fk_tag_target_term_id_term"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag_target")),
        sa.UniqueConstraint(
            "tag_id",
            "column_attribute_id",
            name="uq_tag_target_tag_id_column_attribute_id",
        ),
        sa.UniqueConstraint(
            "tag_id", "column_id", name="uq_tag_target_tag_id_column_id"
        ),
        sa.UniqueConstraint(
            "tag_id", "sql_attribute_id", name="uq_tag_target_tag_id_sql_attribute_id"
        ),
        sa.UniqueConstraint("tag_id", "table_id", name="uq_tag_target_tag_id_table_id"),
        sa.UniqueConstraint("tag_id", "term_id", name="uq_tag_target_tag_id_term_id"),
    )
    op.create_index(
        "ix_tag_target_column_attribute_id",
        "tag_target",
        ["column_attribute_id"],
        unique=False,
    )
    op.create_index(
        "ix_tag_target_column_id", "tag_target", ["column_id"], unique=False
    )
    op.create_index(
        "ix_tag_target_sql_attribute_id",
        "tag_target",
        ["sql_attribute_id"],
        unique=False,
    )
    op.create_index("ix_tag_target_table_id", "tag_target", ["table_id"], unique=False)
    op.create_index("ix_tag_target_term_id", "tag_target", ["term_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tag_target_term_id", table_name="tag_target")
    op.drop_index("ix_tag_target_table_id", table_name="tag_target")
    op.drop_index("ix_tag_target_sql_attribute_id", table_name="tag_target")
    op.drop_index("ix_tag_target_column_id", table_name="tag_target")
    op.drop_index("ix_tag_target_column_attribute_id", table_name="tag_target")
    op.drop_table("tag_target")
    # ### end Alembic commands ###
