# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""add column metadata fields

Revision ID: e2341f8cefb1
Revises: c778a7d94c20
Create Date: 2026-10-02 14:35:00.459769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2341f8cefb1"
down_revision: Union[str, Sequence[str], None] = "c778a7d94c20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("catalog_column", sa.Column("constraints", sa.Text(), nullable=True))
    op.add_column(
        "catalog_column", sa.Column("usage_evidence", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("catalog_column", "usage_evidence")
    op.drop_column("catalog_column", "constraints")
    # ### end Alembic commands ###
