# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""move metadata to column attributes

Revision ID: e718048548d1
Revises: e2341f8cefb1
Create Date: 2026-10-02 14:57:55.255965

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e718048548d1"
down_revision: Union[str, Sequence[str], None] = "e2341f8cefb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "column_attribute", sa.Column("constraints", sa.Text(), nullable=True)
    )
    op.add_column(
        "column_attribute", sa.Column("usage_evidence", sa.Text(), nullable=True)
    )
    op.execute(
        """
        UPDATE column_attribute AS ca
        SET constraints = c.constraints,
            usage_evidence = c.usage_evidence
        FROM column__has_attribute AS h
        JOIN catalog_column AS c ON c.id = h.column_id
        WHERE h.attribute_id = ca.id
        """
    )
    op.drop_column("catalog_column", "usage_evidence")
    op.drop_column("catalog_column", "constraints")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "catalog_column",
        sa.Column("constraints", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "catalog_column",
        sa.Column("usage_evidence", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.execute(
        """
        UPDATE catalog_column AS c
        SET constraints = ca.constraints,
            usage_evidence = ca.usage_evidence
        FROM column__has_attribute AS h
        JOIN column_attribute AS ca ON ca.id = h.attribute_id
        WHERE h.column_id = c.id
        """
    )
    op.drop_column("column_attribute", "usage_evidence")
    op.drop_column("column_attribute", "constraints")
    # ### end Alembic commands ###
