# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""One-off helper used to add SPDX Apache-2.0 headers to NVIDIA-authored
source files. Re-runnable; skips files that already carry an SPDX header.

Run from the repo root:

    uv run --project . python dev_tools/_add_spdx_headers.py

This file is ignored by linters and tests; it only exists so the OSRB
header insertion is reviewable / reproducible.
"""

from __future__ import annotations

import sys
from pathlib import Path

PY_HEADER = (
    "# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES.\n"
    "# All rights reserved.\n"
    "# SPDX-License-Identifier: Apache-2.0\n"
)

JS_HEADER = (
    "// SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES.\n"
    "// All rights reserved.\n"
    "// SPDX-License-Identifier: Apache-2.0\n"
)

# Files that we deliberately do NOT touch.
SKIP_NAMES = {
    "next-env.d.ts",  # auto-generated by Next.js
}

SKIP_DIR_PARTS = {
    "node_modules",
    ".next",
    ".venv",
    "vendor",
    ".git",
    "generated",
    "prisma",  # contains generated client only; keep prisma config separately
}


def iter_source_files(root: Path):
    exts_py = {".py"}
    exts_js = {".ts", ".tsx", ".mjs", ".js"}
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if any(part in SKIP_DIR_PARTS for part in path.parts):
            continue
        if path.name in SKIP_NAMES:
            continue
        if path.suffix in exts_py:
            yield path, PY_HEADER
        elif path.suffix in exts_js:
            yield path, JS_HEADER


def already_has_header(text: str) -> bool:
    head = text[:512]
    return "SPDX-License-Identifier" in head


def insert_header(path: Path, header: str) -> bool:
    text = path.read_text(encoding="utf-8")
    if already_has_header(text):
        return False
    path.write_text(header + "\n" + text, encoding="utf-8")
    return True


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    changed = 0
    skipped = 0
    for path, header in iter_source_files(root):
        if insert_header(path, header):
            changed += 1
            print(f"+ {path.relative_to(root)}")
        else:
            skipped += 1
    print(f"\nupdated: {changed}, already-had-header: {skipped}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
