# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Load pre-generated WideWorldImporters DDL + CSV data into local Postgres.

Reads DDL and CSV files from ``dev_tools/wwi/`` (generated by the MSSQL
migration tool) and applies them to a local Postgres instance.  Does NOT
require an MSSQL connection — all artifacts are pre-generated.

Usage::

    uv run python -m dev_tools.load_wwi_postgres

The target database is ``wideworldimporters`` by default.  Override with
``--database``.  Postgres credentials come from the environment / .env:

    POSTGRES_HOST, POSTGRES_PORT, POSTGRES_USER, POSTGRES_PASSWORD

Pass ``--drop`` to wipe and recreate the database before loading.
"""

from __future__ import annotations

import argparse
import logging
import os
from pathlib import Path

import psycopg

logger = logging.getLogger("dev_tools.load_wwi_postgres")

WWI_DIR = Path(__file__).resolve().parent / "wwi"
DDL_DIR = WWI_DIR / "ddl"
DATA_DIR = WWI_DIR / "data"

DEFAULT_DB = "wideworldimporters"

DDL_FILES_PRE_DATA = [
    "01_schemas.sql",
    "02_sequences.sql",
    "03_tables.sql",
    "04_indexes.sql",
]
DDL_FILES_POST_DATA = [
    "05_fkeys.sql",
    "06_views.sql",
    "07_custom_tables.sql",
]


def _conn_params(db: str = "postgres") -> dict[str, str]:
    return {
        "host": os.environ.get("POSTGRES_HOST", "localhost"),
        "port": os.environ.get("POSTGRES_PORT", "5432"),
        "user": os.environ.get("POSTGRES_USER", "postgres"),
        "password": os.environ.get("POSTGRES_PASSWORD", ""),
        "dbname": db,
    }


def _ensure_database(db: str, *, drop: bool = False) -> None:
    """Create the target database (optionally dropping it first)."""
    admin_db = os.environ.get("POSTGRES_DATABASE", "gsf")
    with psycopg.connect(**_conn_params(admin_db)) as conn:
        conn.autocommit = True
        with conn.cursor() as cur:
            if drop:
                logger.info("Dropping database %s (if exists)...", db)
                cur.execute(f'DROP DATABASE IF EXISTS "{db}"')
            cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (db,))
            if cur.fetchone():
                logger.info("Database %s already exists.", db)
                return
            logger.info("Creating database %s...", db)
            cur.execute(f'CREATE DATABASE "{db}"')


def _apply_ddl(db: str, filenames: list[str]) -> None:
    """Apply a list of DDL SQL files to the database."""
    with psycopg.connect(**_conn_params(db)) as conn:
        conn.autocommit = True
        with conn.cursor() as cur:
            for fname in filenames:
                path = DDL_DIR / fname
                if not path.exists():
                    logger.warning("  DDL file %s not found — skipping.", fname)
                    continue
                logger.info("  Applying %s ...", fname)
                cur.execute(path.read_text())


def _load_csvs(db: str) -> int:
    """COPY all CSV files from data/ into the corresponding tables."""
    if not DATA_DIR.exists():
        logger.error("Data directory %s does not exist.", DATA_DIR)
        return 0

    csvs = sorted(DATA_DIR.glob("*.csv"))
    if not csvs:
        logger.warning("No CSV files found in %s", DATA_DIR)
        return 0

    total_rows = 0
    with psycopg.connect(**_conn_params(db)) as conn:
        conn.autocommit = True
        with conn.cursor() as cur:
            for csv_path in csvs:
                schema_table = csv_path.stem
                parts = schema_table.split(".", 1)
                if len(parts) != 2:
                    logger.warning("  Skipping %s (unexpected name format)", csv_path.name)
                    continue
                schema, table = parts[0].lower(), parts[1].lower()
                qn = f"{schema}.{table}"

                try:
                    with csv_path.open("r") as f:
                        with cur.copy(
                            f"COPY {qn} FROM STDIN WITH "
                            f"(FORMAT csv, HEADER true, NULL '\\N')"
                        ) as copy:
                            while data := f.read(65536):
                                copy.write(data.encode())

                    cur.execute(f"SELECT count(*) FROM {qn}")
                    cnt = cur.fetchone()[0]
                    total_rows += cnt
                    logger.info("  %s.%-40s %10d rows", schema, table, cnt)
                except Exception:
                    logger.error(
                        "  FAILED to load %s", csv_path.name, exc_info=True
                    )

    return total_rows


def load_wwi(database: str = DEFAULT_DB, *, drop: bool = False) -> None:
    """Full load: create DB -> DDL -> CSV data -> FKs/views."""
    logger.info("=" * 60)
    logger.info("Loading WideWorldImporters into Postgres database %r", database)
    logger.info("=" * 60)

    _ensure_database(database, drop=drop)

    logger.info("\n--- Phase 1: DDL (schemas, sequences, tables, indexes) ---")
    _apply_ddl(database, DDL_FILES_PRE_DATA)

    logger.info("\n--- Phase 2: Load CSV data ---")
    total = _load_csvs(database)
    logger.info("  Total: %d rows loaded across all tables.", total)

    logger.info("\n--- Phase 3: Post-data DDL (foreign keys, views) ---")
    _apply_ddl(database, DDL_FILES_POST_DATA)

    logger.info("\n" + "=" * 60)
    logger.info("WideWorldImporters load complete.")
    logger.info("=" * 60)


if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()

    parser = argparse.ArgumentParser(
        description="Load WideWorldImporters into local Postgres"
    )
    parser.add_argument(
        "--database",
        default=DEFAULT_DB,
        help=f"Target database name (default: {DEFAULT_DB}).",
    )
    parser.add_argument(
        "--drop",
        action="store_true",
        help="Drop and recreate the database before loading.",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    load_wwi(args.database, drop=args.drop)
