{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gsf.componentFullname" (list . "backend") }}
  labels:
    {{- include "gsf.componentLabels" (list . "backend") | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end -}}
