{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gsf.componentFullname" (list . "frontend") }}
  labels:
    {{- include "gsf.componentLabels" (list . "frontend") | nindent 4 }}
data:
  {{- range $key, $value := .Values.frontend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end -}}
