{{- if .Values.backend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gsf.componentFullname" (list . "backend") }}
  labels:
    {{- include "gsf.componentLabels" (list . "backend") | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gsf.componentSelectorLabels" (list . "backend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gsf.componentSelectorLabels" (list . "backend") | nindent 8 }}
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-backend.yaml") . | sha256sum }}
        {{- if not .Values.backend.existingSecret }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret-backend.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.backend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gsf.serviceAccountName" (list . "backend" .Values.backend.serviceAccount) }}
      {{- with .Values.backend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ include "gsf.image" (list .Values.backend .Values.image .Chart.AppVersion) }}"
          imagePullPolicy: {{ include "gsf.imagePullPolicy" (list .Values.backend .Values.image) }}
          {{- with .Values.backend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.backend.containerPort | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "gsf.componentFullname" (list . "backend") }}
            - secretRef:
                name: {{ default (include "gsf.componentFullname" (list . "backend")) .Values.backend.existingSecret }}
          {{- with .Values.backend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
