{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gsf.componentFullname" (list . "frontend") }}
  labels:
    {{- include "gsf.componentLabels" (list . "frontend") | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gsf.componentSelectorLabels" (list . "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gsf.componentSelectorLabels" (list . "frontend") | nindent 8 }}
        {{- with .Values.frontend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-frontend.yaml") . | sha256sum }}
        {{- with .Values.frontend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gsf.serviceAccountName" (list . "frontend" .Values.frontend.serviceAccount) }}
      {{- with .Values.frontend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ include "gsf.image" (list .Values.frontend .Values.image .Chart.AppVersion) }}"
          imagePullPolicy: {{ include "gsf.imagePullPolicy" (list .Values.frontend .Values.image) }}
          {{- with .Values.frontend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.frontend.containerPort | quote }}
            - name: HOSTNAME
              value: "0.0.0.0"
          envFrom:
            - configMapRef:
                name: {{ include "gsf.componentFullname" (list . "frontend") }}
            {{- if .Values.frontend.existingSecret }}
            - secretRef:
                name: {{ .Values.frontend.existingSecret }}
            {{- end }}
          {{- with .Values.frontend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
