{{- if and .Values.backend.enabled (not .Values.backend.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gsf.componentFullname" (list . "backend") }}
  labels:
    {{- include "gsf.componentLabels" (list . "backend") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end -}}
